routes/web.php
<?php

/*
 * Copyright (c) 2017 Salah Alkhwlani <yemenifree@yandex.com>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

use App\User;

Route::group([
    'middleware' => \array_merge(['web', 'auth:' . URL::admin('login'), 'admin'], config('admin.middleware', [])),
    'prefix' => URL::admin(),
    'as' => 'admin.',
], function () {
    Route::resource('roles', config('admin.controller.roles') . '\RolesController');
    Route::fakeIdModel('user', User::class);
    Route::changeEnums('users', 'active', config('admin.controller.users') . '\UsersController');
    Route::resource('users', config('admin.controller.users') . '\UsersController');
    Route::get('setting/{module}', '\Modules\Admin\Http\Controllers\SettingController@index');
    Route::post('setting/{module}', [
        'uses' => '\Modules\Admin\Http\Controllers\SettingController@store',
        'as' => 'setting',
    ]);
});

Route::group([
    'middleware' => ['web'],
    'prefix' => URL::admin(),
    'namespace' => config('admin.controller.login'),
    'as' => 'admin.auth.',
], function () {
    Route::get('/login', 'LoginController@login')->name('login');
    Route::post('/login', 'LoginController@store')->name('do-login');
});

Resources/views/index.blade.php
@extends('admin::layouts.admin')

@section('content')


    @include('admin::base.start-row',['panel_title' => trans('admin::common.summary.users')])

    @foreach($User->chunk(4) as $users)
        <div class="row">
            @foreach($users as $user)
                <div class="col-lg-3">
                    <div class="sm-data-box bg-pink">
                        <div class="row ma-0">
                            <div class="col-xs-5 text-center pa-0 icon-wrap-left">
                                <i class="icon-people txt-light"></i>
                            </div>
                            <div class="col-xs-7 text-center data-wrap-right">
                                <h6 class="txt-light">{{ $user->name }}</h6>
                                <span class="txt-light counter counter-anim">{{ $user->users_count }}</span>
                            </div>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    @endforeach
    @include('admin::base.end-row')

@stop

Resources/views/login.blade.php
@extends('admin::layouts.full-width')
@section('content')
    <div class="table-struct full-width full-height">
        <div class="table-cell vertical-align-middle">
            <div class="auth-form  ml-auto mr-auto no-float">
                <div class="panel panel-default card-view mb-0">
                    <div class="panel-heading">
                        <div class="pull-left">
                            <h6 class="panel-title txt-dark">{{ trans('user.Sign In') }}</h6>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="panel-wrapper collapse in">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-sm-12 col-xs-12">
                                    <div class="form-wrap">
                                        {!! BootForm::open()->class('ajax')->action(route('admin.login'))->method('post') !!}
                                            <div class="form-group">
                                                <label class="control-label mb-10"
                                                       for="exampleInputEmail_2">{{ trans('user.Email address') }}</label>
                                                <div class="input-group">
                                                    <input type="email" name="email" class="form-control" required=""
                                                           id="exampleInputEmail_2">
                                                    <div class="input-group-addon"><i class="icon-envelope-open"></i>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label class="control-label mb-10"
                                                       for="exampleInputpwd_2">{{ trans('user.Password') }}</label>
                                                <div class="input-group">
                                                    <input type="password" name="password" class="form-control" required=""
                                                           id="exampleInputpwd_2">
                                                    <div class="input-group-addon"><i class="icon-lock"></i>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="form-group">
                                                <!-- todo link forget password -->
                                                <a class="capitalize-font txt-danger block pt-5 pull-right"
                                                   href="#">{{ trans('user.forgot password') }}</a>
                                                <div class="clearfix"></div>
                                            </div>
                                            <div class="form-group">
                                                <button type="submit"
                                                        class="btn btn-success btn-block">{{ trans('user.sign in') }}</button>
                                            </div>
                                        {!! BootForm::close() !!}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection