routes/web.php
<?php

/*
 * Copyright (c) 2017 Salah Alkhwlani <yemenifree@yandex.com>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

use App\User;

Route::group([
    'middleware' => \array_merge(['web', 'auth:' . URL::admin('login'), 'admin'], config('admin.middleware', [])),
    'prefix' => URL::admin(),
    'as' => 'admin.',
], function () {
    Route::resource('roles', config('admin.controller.roles') . '\RolesController');
    Route::fakeIdModel('user', User::class);
    Route::changeEnums('users', 'active', config('admin.controller.users') . '\UsersController');
    Route::resource('users', config('admin.controller.users') . '\UsersController');
    Route::get('setting/{module}', '\Modules\Admin\Http\Controllers\SettingController@index');
    Route::post('setting/{module}', [
        'uses' => '\Modules\Admin\Http\Controllers\SettingController@store',
        'as' => 'setting',
    ]);
});

Route::group([
    'middleware' => ['web'],
    'prefix' => URL::admin(),
    'namespace' => config('admin.controller.login'),
    'as' => 'admin.auth.',
], function () {
    Route::get('/login', 'LoginController@login')->name('login');
    Route::post('/login', 'LoginController@store')->name('do-login');
});

Resources/views/common/action.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 5/31/16
 * Time: 10:10 AM
 */
?>
@if(count($actions) > 0)
    <div class="dropdown">
        <button class="btn btn-default btn-sm dropdown-toggle" type="button" id="dropdownMenu{{ $info->id }}"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
            {{ trans('common.control') }}
            <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenu{{ $info->id }}">
            @foreach($actions as $action_info)
                <li><a href="{{$action_info['url']}}" class="{{ $action_info['class'] or '' }}" target="{{ $action_info['target'] or '' }}"
                    @foreach(array_except($action_info,['url','class','target']) as $name => $info) data-{{$name}}="{{$info}}" @endforeach >{{$action_info['name']}}</a></li>
            @endforeach
        </ul>
    </div>
@else
    -
@endif

Resources/views/common/end_form.blade.php
</div>
</div>
</div>

@include('admin::base.end-row')

Resources/views/common/footerjs.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 26 ماي، 2016 م
 * Time: 10:10 ص
 */
?>
<div id="alert-sure" class="modal fade in alert-modal" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-body">
                <div class="icon-alert"></div>
                <h3>Warning Massage</h3>
                <p>Are you sure you want to proceed?</p>
            </div>
            <div class="modal-footer">
                <a href="#" data-dismiss="modal" class="alert-btn-close">Cancel</a>
                <a href="#" class="alert-btn-ok">Procced</a>
            </div>
        </div>

    </div>
</div>

{!! Assets::group('admin')->add($assets)->js() !!}
@stack('scripts')
<script>
    $(function () {
        if (typeof $.fn.dataTableExt !== 'undefined') {
            $.fn.dataTableExt.sErrMode = 'none';
        }
    });
</script>
</body>
</html>

Resources/views/common/head.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 26 ماي، 2016 م
 * Time: 10:08 ص
 */
?>
<!doctype html>
<html lang="{{ Config::get('app.locale') }}" dir="{{ \Localization::getCurrentLocaleEntity()->direction() }}">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    {!! app('seotools')->generate() !!}
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta name="viewport" content="width=device-width"/>
    <meta name="_token" content="{!! csrf_token() !!}"/>
    <meta name="_error_class" content="alert alert-danger"/>
    <base href="{{ URL::to('/') }}">
    {!! Assets::group('admin')->add($assets)->css() !!}
    <link rel="icon" type="image/png" href="{{ asset('front/images/favicon.png') }}">

<body class="{{ $class or '' }} {{ \Route2Class::generateClassString() }}" id="content-body">
<!--Preloader-->
<div class="preloader-it">
    <div class="la-anim-1"></div>
</div>
<!--/Preloader-->

Resources/views/common/menu.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 25 ماي، 2016 م
 * Time: 4:02 م
 */
?>
@foreach($items as $item)
    <li @lm-attrs($item) @lm-endattrs>
        @if($item->link)
            <a @lm-attrs($item->link) @if($item->isActive) class="active" @endif @if($item->hasChildren()) data-toggle="collapse" data-target="#{{$item->id}}"
               href="javascript:void(0);" @else href="{!! $item->url() !!}" @endif  @lm-endattrs >
                @if(isset($item->attributes['icon']))
                    <i class="{{$item->attributes['icon']}} mr-10"></i>
                @endif

                {!! $item->title !!}

                @if($item->hasChildren() || isset($item->attributes['count']))
                    <span class="pull-right">
                        @if(isset($item->attributes['count']) && $item->attributes['count'])
                            <span class="label label-success mr-10">{!! showbg($item->attributes['count']) !!} </span>
                            @if($item->isActive)
                                {{ $getuser->makeNoteRead($item->attributes['read'])}}
                            @endif
                        @endif
                        @if($item->hasChildren())
                            <i class="fa fa-fw fa-angle-down"></i>
                        @endif
                    </span>
                @endif

            </a>
        @else
            {!! $item->title !!}
        @endif
        @if($item->hasChildren())
            <ul class="collapse collapse-level-1" id="{{$item->id}}">
                @include('admin::common.menu', array('items' => $item->children()))
            </ul>
        @endif
    </li>
    @if($item->divider)
        <li {!! Lavary\Menu\Builder::attributes($item->divider) !!}></li>
    @endif
@endforeach

Resources/views/common/multi-upload.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 5/31/16
 * Time: 2:39 PM
 */
?>

@if(is_object($values) && count($values) > 0)
    <table class="table table-hover">
        <thead>
        <tr>
            <th>{{trans('admin.common.file name')}}</th>
            <th>{{trans('admin.common.view')}}</th>
        </tr>
        </thead>
        <tbody>
        @foreach($values as $file)
            {!! BootForm::hidden($input.'[]')->value($file->filename)->class('file-'.$file->id) !!}
            <tr class="file-{{$file->id}}">
                <td>{{$file->filename}}</td>
                <td>
                    <a href="{{carfiles($file->filename)}}" class="image-popups" data-effect="mfp-3d-unfold"><i class="fa fa-eye"></i> </a>
                    <a href="{{$file->remove_link}}" id="file-{{$file->id}}" class="ajax"><i class="fa fa-close"></i> </a>
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endif
<div id="{{$id}}" data-input="{{$input}}" class="dropzone needsclick">
    <div class="dz-message needsclick">
        Drop files here or click to upload.<br/>
    </div>
    {{--<div class="fallback">--}}
    {{--<input name="file" type="file" multiple />--}}
    {{--</div>--}}
</div>

@push('scripts')
<script type="application/javascript">
    $().ready(function () {
        var myDropzone = new Dropzone("#{{$id}}", {
            //paramName: "{{$input}}",
            uploadMultiple: true,
            addRemoveLinks: true,
            autoProcessQueue: true,
            //dictDefaultMessage: '',
            url: "{{UrlLang('ajax/upload')}}",
            init: function () {
                this.on("addedfile", function (file) {

                    NProgress.start();
                });
                this.on("removedfile", function (fileinfo) {
                    console.log($.md5(fileinfo.name));
                    $('input[id="' + $.md5(fileinfo.name) + '"]').remove();
                });
                this.on("complete", function (file) {
                    NProgress.done();
                });
                this.on("error", function (file) {
                    notie.alert(3, 'Sorry, try upload file again', 5);
                });
                this.on("success", function (file, res) {
                    $('<input>').attr({
                        type: 'hidden',
                        id: $.md5(file.name),
                        name: '{{$input}}[]',
                        value: res.filename
                    }).appendTo('.ajax');
                });
            }
        });
    });
</script>
@endpush

Resources/views/common/navbar.blade.php
<!-- Top Menu Items -->
<nav class="navbar navbar-inverse navbar-fixed-top">
    <a id="toggle_nav_btn" class="toggle-left-nav-btn inline-block mr-20 pull-left" href="javascript:void(0);">
        <i class="fa fa-bars"></i>
    </a>
    <a href="{{ url(env('APP_ADMIN_PREFIX','admin')) }}">
        <img class="brand-img pull-left" src="{{ asset('control/dist/img/logo.png') }}" />
    </a>
    <ul class="nav navbar-right top-nav pull-right">
        <li class="dropdown">
            <a href="#" class="dropdown-toggle pr-0" data-toggle="dropdown">
                <img class="user-auth-img img-circle" src="{{ (!\Sentinel::guest() && isset(\Sentinel::getUser()->logo)) ? \Sentinel::getUser()->logo : asset('control/dist/img/user1.png') }}" />
                <span> {{ Sentinel::getUser()->name }}</span>
                {{--<span class="user-online-status"></span>--}}
            </a>
            <ul class="dropdown-menu user-auth-dropdown" data-dropdown-in="fadeIn" data-dropdown-out="fadeOut">
                <li><a href="{{ route('admin.users.edit',['id' => Sentinel::getUser()]) }}"><i class="fa fa-fw fa-user"></i> {{ trans('user.profile') }}</a></li>
                <li><a href="{{ route('admin.settings.app') }}"><i class="fa fa-fw fa-user"></i> {{ trans('user.settings') }}</a></li>
                <li><a href="{{ route('web.auth.logout') }}"><i class="fa fa-fw fa-power-off"></i> {{ trans('user.logout') }}</a></li>
            </ul>
        </li>
    </ul>
</nav>
<!-- /Top Menu Items -->

Resources/views/common/notifications.blade.php
@foreach(Sentinel::getUser()->notifications()->with(['body','from'])->orderby('id','desc')->paginate(10) as $noti)
    <li>
        <i class="si si-wallet text-success"></i>
        <a class="font-w600" style="display: inline-block;" href="{{ $noti->url  }}"> {{ $noti->notify_body  }}</a>
        <div><a href="{{ UrlLang(env('APP_ADMIN_PREFIX','admin').'/user/'.$noti->from->id) }}">{{ $noti->from->username }}</a></div>
        <div>
            <small class="text-muted">{{ $noti->created_at->diffForHumans() }}</small>
        </div>
    </li>
@endforeach

Resources/views/common/select2-depend.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 6/16/16
 * Time: 12:25 PM
 */
?>

var depdrop_{{$name}} = {"depends":["{{$depends}}"],"url":"{{$url}}","loadingText":"{{trans('admin.common.Loading')}}","initialize":true};
kvInitPlugin('#{{$name}}', function(){
if (jQuery('#{{$name}}').data('depdrop')) { jQuery('#{{$name}}').depdrop('destroy'); }
jQuery('#{{$name}}').depdrop(depdrop_{{$name}});

});
kvInitPlugin(jQuery('#{{$name}}').kvSelector(), function(){
if (jQuery('#{{$name}}').data('select2')) { jQuery('#{{$name}}').select2('destroy'); }
jQuery.when(jQuery('#{{$name}}').select2(select2_980572ea)).done(initS2Loading('model','s2options_d6851687'));
});
initDepdropS2('{{$name}}',"{{trans('admin.common.Loading')}}");

Resources/views/common/side-overlay.blade.php
<!-- Side Overlay-->
<div id="side-overlay">
    <!-- Side Overlay Scroll Container -->
    <div id="side-overlay-scroll">
        <!-- Side Header -->
        <div class="side-header side-content">
            <!-- Layout API, functionality initialized in App() -> uiLayoutApi() -->
            <button class="btn btn-default pull-right" type="button" data-toggle="layout"
                    data-action="side_overlay_close">
                <i class="fa fa-times"></i>
            </button>
            <span>
                <!--<img class="img-avatar img-avatar32" src="assets/img/avatars/avatar10.jpg" alt="">-->
                <a href="{{ UrlLang(env('APP_ADMIN_PREFIX','admin').'/notifications') }}" class="font-w600 push-10-l">{{ trans('admin.common.notification') }} </a>
            </span>
        </div>
        <!-- END Side Header -->

        <!-- Side Content -->
        <div class="side-content remove-padding-t">
            <!-- Notifications -->
            <div class="block pull-r-l">
                <div class="block-header bg-gray-lighter">
                    <ul class="block-options">
                        <li>
                            <a class="ajax" data-nonconfirm="1" data-page="1" href="{{ UrlLang(env('APP_ADMIN_PREFIX','admin').'/lastactivity') }}"><i class="si si-refresh"></i></a>
                        </li>
                        <li>
                            <button type="button" data-toggle="block-option" data-action="content_toggle"></button>
                        </li>
                    </ul>
                    <h3 class="block-title">{{ trans('admin.common.recent activity') }}</h3>
                </div>
                <div class="block-content">
                    <!-- Activity List -->
                    <div class="container-noti">
                        <ul class="list list-activity" id="list-activity">
                            @include('admin.common.notifications')
                        </ul>
                    </div>
                    <div class="text-center pag-list-activity">
                        <small><a class="ajax list-activity-btn wihtout-confi" data-nonconfirm="1" data-page="2" href="{{ UrlLang(env('APP_ADMIN_PREFIX','admin').'/lastactivity') }}">{{ trans('admin.common.load-more.Load More..') }}</a></small>
                    </div>
                </div>
            </div>
            <!-- END Notifications -->
        </div>
        <!-- END Side Content -->
    </div>
    <!-- END Side Overlay Scroll Container -->
</div>
<!-- END Side Overlay -->

Resources/views/common/sidebar.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: salah
 * Date: 25 ماي، 2016 م
 * Time: 12:16 م
 */
?>

<!-- Left Sidebar Menu -->
<div class="fixed-sidebar-left">
    <ul class="nav navbar-nav side-nav nicescroll-bar">
        @include('admin::common.menu', array('items' => Menu::get('Admin')->roots()))
    </ul>
</div>

Resources/views/common/start_form.blade.php
@include('admin::base.start-row')

@if (isset($form_title) && !empty($form_title) && !isset($hide_form_title))
    <h6 class="txt-dark capitalize-font">
        <i class="icon-pencil mr-10"></i>
        {{ $form->getData('title',$form_title) }}
        @if($form->getData('hasLang',false))
            <div class="lang-switch-box">
                <div class="btn-group">
                    @foreach(\Localization::getSupportedLocales() as $locale)
                        <button type="button"
                                class="btn {{ $locale->key() == \Localization::getCurrentLocale() ? 'btn-success' : 'btn-default' }}"
                                data-key="{{ $locale->key() }}">{{ $locale->native() }}</button>
                    @endforeach
                </div>
                <input type="hidden" value="{{  \Localization::getCurrentLocale() }}" name="lang-switch"
                       id="lang-switch">
            </div>
        @endif
    </h6>
    <hr style="margin-top: 0;">
@endif

<div class="row">
    <div class="col-md-12">
        <div class="form-wrap">

Resources/views/common/upload-inline.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 5/31/16
 * Time: 2:39 PM
 */
?>
<div class="form-group upload-inline">
    <div class="input-group">
        <span class="input-group-btn">
            <a id="lfm" data-input="thumbnail" data-preview="holder" class="btn btn-primary">
                <i class="fa fa-picture-o"></i> Choose
            </a>
        </span>
        {!! BootForm::text($label, $input)->placeholder($label)->id('thumbnail') !!}
        {{--<input id="thumbnail" class="form-control" type="text" name="filepath">--}}
    </div>
    <img id="holder" style="margin-top:15px;max-height:100px;">
</div>
@push('scripts')
<script type="application/javascript">
    $().ready(function () {
        $('#lfm').filemanager('image');
    });
</script>
@endpush

Resources/views/common/upload.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: root
 * Date: 5/31/16
 * Time: 2:39 PM
 */
?>
<div class="upload-files">
    {!! BootForm::hidden($input) !!}
    @if(isset($is_img))
        <div id="img-thumb-preview">
            <img id="img-thumb-{{$id}}" data-input="photo" class="avatar border-gray"
                 src="{{ !empty($old_img) ? $old_img : asset('public/'.env('APP_ADMIN_PREFIX','admin').'/assets/img/default-avatar.png') }}">
        </div>
    @endif
    @if(!isset($nbtn))
        <div id="{{$id}}" data-input="{{$input}}"
             class="btn btn-default margin-t-5 needsclick icobutton icobutton--thumbs-up">
            <i class="fa fa-upload"></i> {{ $upload or trans('userprofile.upload.Upload') }}
        </div>
        @push('scripts')
        <script type="application/javascript">
            $().ready(function () {
                Dropzone.autoDiscover = false;
                var myDropzone = new Dropzone("#{{$id}}", {
                    uploadMultiple: false,
                    addRemoveLinks: false,
                    dictDefaultMessage: '',
//                    maxFiles: 1,
                    url: "{{UrlLang('ajax/upload')}}",
                    init: function () {
                        this.on("maxfilesexceeded", function(file){
                            this.removeAllFiles();
                            this.addFile(file);
                        });
                        this.on("addedfile", function (file) {
                            $('#{{$id}}').removeClass('done-upload');
                            NProgress.start();
                        });
                        this.on("complete", function (file) {
                            NProgress.done();
                        });
                        this.on("error", function (file) {
                            file.status = Dropzone.QUEUED;
                            notie.alert(3, 'Sorry, try upload file again', 5);
                        });
                        this.on("success", function (file, res) {
                            //file.status = Dropzone.QUEUED;
                            $('#{{$id}}').addClass('done-upload');
                            $('#{{$id}} i').removeClass('fa-upload').addClass('fa-check');
                            //laravel.alert('');
                            //console.log('upload success...');
                            @if(isset($is_img))
                            $('#img-thumb-{{$id}}').attr('src', res.url);
                            @endif
                            $('input[name="' + $('#{{$id}}').data('input') + '"]').val(res.filename);
                        });
                    }
                });
                $('#upload-submit-{{$id}}').on('click', function (e) {
                    e.preventDefault();
                    //trigger file upload select
                    $("#{{$id}}").trigger('click');
                });
            });
        </script>
@endpush
@endif
</div>